import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaAws,
  FaDatabase,
  FaBootstrap,
  FaDocker,
  FaGithub,
  FaTools,
  FaRegLightbulb,
  FaJava,
  FaLock,
  FaShieldAlt,
  FaTachometerAlt,
  FaUniversalAccess,
  FaBug,
  FaServer,
  FaCogs,
} from 'react-icons/fa'
import {
  SiNextdotjs,
  SiAngular,
  SiVuedotjs,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiJest,
  SiTestinglibrary,
  SiWebpack,
  SiJenkins,
  SiGraphql,
  SiVite,
  SiEslint,
  SiPrettier,
  SiFigma,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiSpringboot,
  SiCypress,
  SiBabel,
  SiStyledcomponents,
} from 'react-icons/si'

const skillIconMap = {
  'React.js': FaReact,
  'React Hooks': FaReact,
  Angular: SiAngular,
  'Vue.js': SiVuedotjs,
  'Next.js': SiNextdotjs,
  'Node.js': FaNodeJs,
  'JavaScript (ES6+)': SiJavascript,
  TypeScript: SiTypescript,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  'Tailwind CSS': SiTailwindcss,
  Bootstrap: FaBootstrap,
  'Styled Components': SiStyledcomponents,
  'CSS Modules': FaCss3Alt,
  'Responsive/Adaptive Design': FaTachometerAlt,
  Webpack: SiWebpack,
  Vite: SiVite,
  Babel: SiBabel,
  Figma: SiFigma,
  Java: FaJava,
  'Spring Boot': SiSpringboot,
  REST: FaServer,
  GraphQL: SiGraphql,
  JSON: FaCogs,
  JWT: FaLock,
  OAuth: FaLock,
  CORS: FaShieldAlt,
  'API Security': FaShieldAlt,
  Caching: FaTachometerAlt,
  Logging: FaBug,
  Jest: SiJest,
  'React Testing Library': SiTestinglibrary,
  Cypress: SiCypress,
  Playwright: FaTools,
  'Unit/Integration/E2E Testing': FaTools,
  'Test Automation': FaTools,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  SQL: FaDatabase,
  'Schema Design': FaDatabase,
  'Advanced Queries': FaDatabase,
  Git: FaGitAlt,
  'GitHub Actions': FaGithub,
  Jenkins: SiJenkins,
  Docker: FaDocker,
  AWS: FaAws,
  'CI/CD Pipelines': FaCogs,
  'Performance Monitoring': FaTachometerAlt,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  'Accessibility (WCAG 2.1 AA)': FaUniversalAccess,
  'Frontend Performance Optimization': FaTachometerAlt,
  'Frontend Security': FaShieldAlt,
  'Agile/SCRUM': FaCogs,
  'Client-Side Debugging': FaBug,
  OOP: FaCogs,
  'Design Patterns': FaCogs,
}

export const getSkillIcon = (skill) => skillIconMap[skill] || FaRegLightbulb
