import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaGitAlt,
  FaAws,
  FaCloud,
  FaMobileAlt,
  FaShareAlt,
  FaPython,
  FaDatabase,
  FaBootstrap,
  FaDocker,
  FaClipboardCheck,
  FaGithub,
  FaTools,
  FaRegLightbulb,
  FaCloudUploadAlt,
} from 'react-icons/fa'
import {
  SiNextdotjs,
  SiAngular,
  SiVuedotjs,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiRedux,
  SiJest,
  SiTestinglibrary,
  SiWebpack,
  SiJenkins,
  SiGraphql,
  SiPnpm,
  SiAmazonaws,
} from 'react-icons/si'

const skillIconMap = {
  'React.js': FaReact,
  Angular: SiAngular,
  'Vue.js': SiVuedotjs,
  'Next.js': SiNextdotjs,
  'Node.js': FaNodeJs,
  'JavaScript (ES6+)': SiJavascript,
  TypeScript: SiTypescript,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  SASS: FaSass,
  SQL: FaDatabase,
  Python: FaPython,
  'Tailwind CSS': SiTailwindcss,
  Bootstrap: FaBootstrap,
  'Responsive Design': FaMobileAlt,
  Redux: SiRedux,
  Vuex: SiVuedotjs,
  'Context API': FaShareAlt,
  Jest: SiJest,
  'React Testing Library': SiTestinglibrary,
  Enzyme: FaTools,
  Webpack: SiWebpack,
  Git: FaGitAlt,
  AWS: FaAws,
  Docker: FaDocker,
  Jenkins: SiJenkins,
  GraphQL: SiGraphql,
  'REST APIs': FaCloud,
  PNPM: SiPnpm,
  'Agile/Scrum': FaClipboardCheck,
  'CI/CD': FaCloudUploadAlt,
  GitHub: FaGithub,
  CodeCommit: SiAmazonaws,
}

export const getSkillIcon = (skill) => skillIconMap[skill] || FaRegLightbulb
