import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaGitAlt,
  FaAws,
  FaCloud,
  FaMobileAlt,
  FaShareAlt,
  FaPython,
  FaDatabase,
  FaBootstrap,
  FaDocker,
  FaClipboardCheck,
  FaGithub,
  FaTools,
  FaRegLightbulb,
  FaCloudUploadAlt,
  FaLock,
  FaShieldAlt,
} from 'react-icons/fa'
import {
  SiNextdotjs,
  SiAngular,
  SiVuedotjs,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiRedux,
  SiJest,
  SiTestinglibrary,
  SiWebpack,
  SiJenkins,
  SiGraphql,
  SiPnpm,
  SiAmazonwebservices,
  SiVite,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiPlaywright,
  SiCypress,
  SiFigma,
  SiNpm,
  SiYarn,
  SiGithubactions,
} from 'react-icons/si'

const skillIconMap = {
  'React.js': FaReact,
  Angular: SiAngular,
  'Vue.js': SiVuedotjs,
  'Next.js': SiNextdotjs,
  'Node.js': FaNodeJs,
  'JavaScript (ES6+)': SiJavascript,
  TypeScript: SiTypescript,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  SASS: FaSass,
  SQL: FaDatabase,
  Python: FaPython,
  'Tailwind CSS': SiTailwindcss,
  Bootstrap: FaBootstrap,
  'Responsive Design': FaMobileAlt,
  Redux: SiRedux,
  Vuex: SiVuedotjs,
  'Context API': FaShareAlt,
  'State Management (Redux / Context)': SiRedux,
  'React Hooks & Advanced Patterns': FaReact,
  'CSS Modules / Styled Components': FaCss3Alt,
  Jest: SiJest,
  'React Testing Library': SiTestinglibrary,
  'End-to-End Testing (Playwright / Cypress)': SiPlaywright,
  Playwright: SiPlaywright,
  Cypress: SiCypress,
  Enzyme: FaTools,
  Webpack: SiWebpack,
  Vite: SiVite,
  Babel: SiBabel,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  'npm / yarn': SiNpm,
  npm: SiNpm,
  yarn: SiYarn,
  Git: FaGitAlt,
  AWS: FaAws,
  Docker: FaDocker,
  Jenkins: SiJenkins,
  'GitHub Actions': SiGithubactions,
  GraphQL: SiGraphql,
  'REST APIs': FaCloud,
  PNPM: SiPnpm,
  'Agile/Scrum': FaClipboardCheck,
  'CI/CD': FaCloudUploadAlt,
  GitHub: FaGithub,
  CodeCommit: SiAmazonwebservices,
  'Figma (Design Handoff)': SiFigma,
  Figma: SiFigma,
  'Web Fundamentals (Event Loop, HTTP, Caching)': FaCloud,
  'Frontend Security (XSS, CSRF, CORS)': FaShieldAlt,
  'Authentication (JWT, OAuth)': FaLock,
}

export const getSkillIcon = (skill) => skillIconMap[skill] || FaRegLightbulb
